// KA-026 transmission log (v5).
// Each transmission `dropAt` is in PT (-07:00 covers the entire run; no DST flip).
// `body` is rendered exactly as written (whitespace + line breaks preserved, typewriter character-by-character).
// `crew` is the per-transmission Crew Manifest snapshot. Order is fixed; statuses evolve.

window.TRANSMISSIONS = [
  {
    id: "T1",
    label: "SIGNAL_INTERCEPTED",
    act: "I",
    dropAt: "2026-04-27T12:00:00-07:00",
    header: "TRANSMISSION 01 · SIGNAL INTERCEPTED · DAY 1",
    body:
`MAYDAY · MAYDAY · MAYDAY

THIS IS THE KAPPA ALPHA ORDER.
THE KREWSHIP HAS GONE DOWN.

WE WERE EXPLORING LAKE LAG.
A LIGHT RAIN BECAME A TEMPEST.
LIGHTNING STRUCK THE MAST.
THE HULL TOOK ON WATER.

WE WASHED ASHORE ON UNKNOWN LAND.
WE DUBBED IT KA ISLAND.

FILIP RIGGED A HOTSPOT FROM
HIS MAC MINI. WE HAVE BYTES.
NOT MANY. ENOUGH FOR THIS.

FOOD: ONE MONTH AT BEST.
WATER: WE FOUND SOME.
RESCUE: UNCLEAR.

IF YOU ARE RECEIVING THIS —
WE NEED HELP BY MAY 2.

NEXT SIGNAL IN 24 HOURS.
STAND BY.`,
    crew: [
      ["FILIP",     "MAINTAINING SIGNAL"],
      ["MERILL",    "GUARDING PERIMETER"],
      ["PEARSON",   "UNHARMED"],
      ["TWEAKSNER", "PUNCHING WAVES"],
      ["CHASE",     "HIGH AURA"],
      ["JATWANI",   "UNCONSCIOUS"]
    ]
  },

  {
    id: "T2",
    label: "THE_RAIDERS",
    act: "I",
    dropAt: "2026-04-28T12:00:00-07:00",
    header: "TRANSMISSION 02 · DAY 2 · THE RAIDERS",
    body:
`WE WERE NOT THE FIRST HERE.

THEY CAME ON OUR FIRST NIGHT.
EMERGED FROM THE DARK.
WEAPONS IN HAND.
SLASHED OUR MEMBERS.
STOLE OUR SUPPLIES.

WE FOUGHT WHAT WE COULD.

MERILL IS 30 V 1 AGAINST THEM.
HE IS NOT SLEEPING.
TWEAKSNER IS PUNCHING THE WAVES.
CHASE HIT THE PIECE SO HARD
HIS VO2 MAX DOUBLED.
CHARLIE GOES, "DAMN."

WE ARE COMPLETELY MAROONED.

NEXT SIGNAL TOMORROW.`,
    crew: [
      ["FILIP",     "MAINTAINING SIGNAL"],
      ["MERILL",    "30 V 1"],
      ["PEARSON",   "RATIONING"],
      ["TWEAKSNER", "PUNCHING WAVES"],
      ["CHASE",     "VO2 MAX DOUBLED"],
      ["JATWANI",   "UNCONSCIOUS"]
    ]
  },

  {
    id: "T3",
    label: "FADING",
    act: "I",
    dropAt: "2026-04-29T12:00:00-07:00",
    header: "TRANSMISSION 03 · DAY 3 · FADING",
    body:
`THREE DAYS SINCE THE WRECK.
THREE DAYS OF SILENCE FROM YOU.

RATIONS THIN. THE BOYS ARE COOKED.
PEARSON HAS LOST WEIGHT.
JACOB IS CRYING ABOUT IT.

JAMES E IS HYPE THAT THE WATER
WASHED THE OIL OFF THE CHICKEN.
SMALL WINS.

THE RAIDERS HAVE A NAME NOW.
WE CALL THEM THE KARAIDERS.

UNSPEAKABLE THOUGHTS HAVE EMERGED.
AS DELICIOUS AS JATWANI MUST BE —
WE ARE HOLDING THE LINE.

FILIP SAYS THE BYTES ARE GOING.
NEXT SIGNAL TOMORROW.`,
    crew: [
      ["FILIP",     "BYTES FAILING"],
      ["MERILL",    "30 V 1 STILL"],
      ["PEARSON",   "LOSING WEIGHT"],
      ["TWEAKSNER", "PUNCHING WAVES"],
      ["CHASE",     "ASCENDING"],
      ["JATWANI",   "LOOKING DELICIOUS"]
    ]
  },

  {
    id: "T4",
    label: "RESCUE_CANCELLED",
    act: "II",
    dropAt: "2026-04-30T12:00:00-07:00",
    header: "TRANSMISSION 04 · RESCUE CANCELLED",
    stamp: "RESCUE CANCELLED",
    body:
`WE TOOK A VOTE.

NO ONE IS COMING.
WE KNOW THAT NOW.

A SLOW DEATH IN A BATTLE OF
ATTRITION. MINIMUM AURA.

INSTEAD —
WE TAKE EVERYTHING WE HAVE.
THE RUM. THE WHISKY.
THE ALEX MANE CHICKEN.

WE THROW ONE LAST BLOWOUT.

THE LAST RAVE ON EARTH.
SATURDAY. MAY SECOND.
ON KA ISLAND.

OWN OUR END. MAXIMUM AURA.

IF YOU ARE RECEIVING THIS —
COME FIND US.

NEXT SIGNAL TOMORROW.`,
    crew: [
      ["FILIP",     "BYTES CRITICAL"],
      ["MERILL",    "NOT SLEEPING"],
      ["PEARSON",   "DETERIORATING"],
      ["TWEAKSNER", "PUNCHING WAVES"],
      ["CHASE",     "MAXIMUM AURA"],
      ["JATWANI",   "[REDACTED]"]
    ]
  },

  {
    id: "T5",
    label: "TWENTY_FOUR_HOURS",
    act: "II→III",
    dropAt: "2026-05-01T12:00:00-07:00",
    header: "TRANSMISSION 05 · 24 HOURS",
    body:
`IT IS TOMORROW.

THE SUN WILL RISE ONE LAST TIME
AND THEN IT WILL GO DOWN.
AND WE WILL GO DOWN WITH IT.

WE BUILT A STAGE
FROM THE BONES OF THE KREWSHIP.
THE PLEDIGTOS WHO BUILT HER
ARE TEARING HER APART.

THE KARAIDERS HAVE GONE QUIET.
WE THINK THEY ARE WAITING TOO.

COME AT TWO PM.
DRESS FOR THE BEACH.
BRING A BORG.

SEE YOU ON THE ISLAND.`,
    crew: [
      ["FILIP",     "LAST PACKETS"],
      ["MERILL",    "EYES OPEN"],
      ["PEARSON",   "NEAR-CADAVEROUS"],
      ["TWEAKSNER", "PUNCHING WAVES"],
      ["CHASE",     "TRANSCENDED"],
      ["JATWANI",   "[REDACTED]"]
    ]
  },

  {
    id: "T6",
    label: "FINAL_TRANSMISSION",
    act: "III",
    dropAt: "2026-05-02T10:00:00-07:00",
    header: "FINAL TRANSMISSION · SIGNAL TERMINATED",
    body:
`SIGNAL LOCKED.

YOU HAVE BEEN FOUND.
OR YOU HAVE BEEN RESCUED.
IT DOES NOT MATTER ANYMORE.

THE BYTES ARE GONE.
FILIP'S MAC MINI HAS DIED.

IF YOU ARE RECEIVING THIS,
YOU ARE ALREADY ON THE WAY.

THE LAST RAVE HAS BEGUN.

KAPPA ALPHA · OUT.`,
    crew: [
      ["FILIP",     "MAC MINI DEAD"],
      ["MERILL",    "STILL HERE"],
      ["PEARSON",   "UPRIGHT"],
      ["TWEAKSNER", "UNDEFEATED"],
      ["CHASE",     "ON STAGE"],
      ["JATWANI",   "NEVER SPOKE"]
    ]
  }
];

window.SIGNAL_ANCHORS = {
  firstDrop: "2026-04-27T12:00:00-07:00",
  partyStart: "2026-05-02T14:00:00-07:00",
  signalTerminated: "2026-05-02T10:00:00-07:00"
};
