// KA-026 transmission log.
// Each transmission `dropAt` is in PST/PDT (-07:00 covers the entire run; no DST flip).
// `body` is rendered exactly as written (whitespace + line breaks preserved, typewriter character-by-character).

window.TRANSMISSIONS = [
  {
    id: "T1",
    label: "SIGNAL_INTERCEPTED",
    act: "I",
    dropAt: "2026-04-20T12:00:00-07:00",
    header: "TRANSMISSION 01 · SIGNAL INTERCEPTED · DAY 1",
    body:
`MAYDAY · MAYDAY · MAYDAY

THIS IS THE KAPPA ALPHA ORDER.
THE KREWSHIP HAS GONE DOWN.

WE WERE EXPLORING LAKE LAG.
A STORM TOOK US.
WE WASHED ASHORE ON UNKNOWN LAND.

FILIP RIGGED A HOTSPOT FROM
HIS MAC MINI. WE HAVE BYTES.
NOT MANY. ENOUGH FOR THIS.

FOOD: ONE MONTH AT BEST.
WATER: WE FOUND SOME.
RESCUE: UNCLEAR.

IF YOU ARE RECEIVING THIS —
WE NEED HELP BY MAY 2.

NEXT SIGNAL IN 72 HOURS.
STAND BY.`
  },

  {
    id: "T2",
    label: "DAY_3",
    act: "I",
    dropAt: "2026-04-23T12:00:00-07:00",
    header: "TRANSMISSION 02 · DAY 3",
    body:
`STILL NO RESCUE.

THE KREWSHIP IS SPLIT IN TWO
ON THE BEACH. WE SALVAGED
WHAT WE COULD.

THE ISLAND IS NOT EMPTY.
THERE ARE OTHERS HERE.
RAIDERS. THEY COME AT NIGHT
FOR THE SUPPLIES.

MERILL IS 30 V 1 AGAINST THEM.
HE IS NOT SLEEPING.

NO BOATS. NO PLANES. NOTHING.
THE SIGNAL IS GETTING WEAKER.

NEXT SIGNAL SUNDAY.`
  },

  {
    id: "T3",
    label: "FADING",
    act: "I",
    dropAt: "2026-04-26T12:00:00-07:00",
    header: "TRANSMISSION 03 · DAY 6 · FADING",
    body:
`SIX DAYS SINCE THE WRECK.
SIX DAYS OF SILENCE FROM YOU.

WE HAVE ONE WEEK LEFT.
RATIONS THIN. THE BOYS ARE COOKED.
FIEN HAS LOST WEIGHT.

THE RAIDERS HAVE A NAME NOW.
WE CALL THEM THE KARAIDERS.

WE CAN HEAR THEM AT NIGHT.
THEY SOUND LIKE LAUGHTER.

IF ANY OF YOU ARE LISTENING —
PLEASE.
WE ARE HERE. STANFORD. KAPPA ALPHA.
WE ARE NOT MAKING THIS UP.

FILIP SAYS THE BYTES ARE GOING.
NEXT SIGNAL TUESDAY.`
  },

  {
    id: "T4",
    label: "RESCUE_CANCELLED",
    act: "II",
    dropAt: "2026-04-28T12:00:00-07:00",
    header: "TRANSMISSION 04 · RESCUE CANCELLED",
    stamp: "RESCUE CANCELLED",
    body:
`WE TOOK A VOTE.

NO ONE IS COMING.
WE KNOW THAT NOW.

HERE IS THE PLAN:
FOUR DAYS OF SUPPLIES LEFT.
WE ARE PUTTING ALL OF THEM
INTO ONE LAST DAY.

THE RUM. THE WHISKY.
THE ALEX MANE CHICKEN.
EVERYTHING WE HAVE.

THE LAST RAVE ON EARTH.
SATURDAY. MAY SECOND.
ON OUR ISLAND.

IF YOU ARE RECEIVING THIS —
AND YOU WANT TO COME —
YOU KNOW WHERE TO FIND US.

NEXT SIGNAL FRIDAY.`
  },

  {
    id: "T5",
    label: "TWENTY_FOUR_HOURS",
    act: "II→III",
    dropAt: "2026-05-01T12:00:00-07:00",
    header: "TRANSMISSION 05 · 24 HOURS",
    body:
`IT IS TOMORROW.

THE SUN WILL RISE ONE LAST TIME
AND THEN IT WILL GO DOWN.
AND WE WILL GO DOWN WITH IT.

WE FOUND EVERYTHING WE NEED.
RUM. FIRE. MUSIC.
WE BUILT A STAGE
FROM THE BONES OF THE KREWSHIP.

THE KARAIDERS HAVE GONE QUIET.
WE THINK THEY ARE WAITING TOO.

COME AT TWO PM.
BRING NOTHING BUT YOURSELF.
DRESS TO SURVIVE.

SEE YOU ON THE ISLAND.`
  },

  {
    id: "T6",
    label: "THE_RESCUE_IS_ACTIVE",
    act: "III",
    dropAt: "2026-05-02T14:00:00-07:00",
    header: "TRANSMISSION 06 · THE RESCUE IS ACTIVE",
    body:
`SIGNAL LOCKED.

YOU HAVE BEEN RESCUED.
OR YOU HAVE BEEN FOUND.
IT DOES NOT MATTER ANYMORE.

THE LAST RAVE HAS BEGUN.`
  },

  {
    id: "T7",
    label: "FINAL_TRANSMISSION",
    act: "coda",
    dropAt: "2026-05-04T12:00:00-07:00",
    header: "FINAL TRANSMISSION · SIGNAL TERMINATED",
    body:
`WE DIDN'T MAKE IT.
BUT YOU DID.

THANK YOU FOR COMING TO FIND US.

THE BYTES ARE GONE.
FILIP'S MAC MINI HAS DIED.

THIS IS THE LAST SIGNAL.
KAPPA ALPHA · OUT.`
  }
];

window.SIGNAL_ANCHORS = {
  firstDrop: "2026-04-20T12:00:00-07:00",
  partyStart: "2026-05-02T14:00:00-07:00",
  signalTerminated: "2026-05-04T12:00:00-07:00"
};
