// Source: KA_Members.csv (Drive). Cleaned: trimmed whitespace, dropped empty rows + header.
// Used by api/respond.js to pick a random KA name to greet the receiver with.
module.exports = [
  "Nick Allen",
  "Jack Baldwin",
  "Theoren Brouillette",
  "Luca Camponovo",
  "Nico Di Borgoricco",
  "Yahli Einav",
  "James Eklund",
  "Dean Greyserman",
  "Filip Henriksson",
  "Rishi Jain",
  "Guido Leonardi",
  "Chase McFarland",
  "Jack Merrill",
  "Konstantinos Michalopoulos",
  "Clayton Moore",
  "Griffen Price",
  "Seth Rhodes",
  "Alex Rottman",
  "Rowan Schnebly",
  "Ben Shaper",
  "Berk Yalcinkaya",
  "Henry Clark",
  "Pearson Ehrich",
  "Dylan Jatwani",
  "Jack Lipschultz",
  "Kostas Mathiopoulos",
  "Joe Roberts",
  "Prady Saligram",
  "Krithik Seela",
  "Charlie Seymour",
  "Jacob Sinsheimer",
  "Andreas Tempereau",
  "Luke Tusher",
  "Gavin West",
  "Niki Yoon",
  "Martin Andra-Thomas",
  "Pablo Barrera",
  "Lucas Burgett",
  "Cole Cline",
  "Reece Davidoff",
  "Ricky Di Borgoricco",
  "Will Hesp",
  "Derek Jain",
  "Preston Jernegan",
  "Gary Liu",
  "Hubert Lu",
  "Oscar Montgomery",
  "James Rhee",
  "Kai Schmitt",
  "Krish Sharma",
  "Joseph Shelby",
  "George Weiksner"
];
